version: "3.8"
services:
  nginx:
    image: nginx
    container_name: 'nginx-proxy'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    ports:
      - "3000:3000"
    links:
      - athena_engine
  athena_engine:
    build: ./
    container_name: 'athena-engine'
    image: athenaengine_server
    links:
      - mongo
  mongo:
    image: mongo
    container_name: 'mongo-db'
    volumes:
      - .data/mongo-db:/data/db

